import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Papa from 'papaparse';
import QRCode from 'qrcode';
import { authClient, startGoogleLogin, signOutGoogle } from './auth.js';
import { cloudEnabled, cloudRequest } from './cloud.js';
import './style.css';
import './compass-theme.css';
import './print.css';

const API = (import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
let session = sessionStorage.getItem('lecturer-session') || '';
async function request(path, body, method) {
  if (cloudEnabled) return cloudRequest(path, body, method);
  const response=await fetch(`${API}/api${path}`,{method:method || (body?'POST':'GET'),headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Authorization:`Bearer ${session}`}:{})},body:body?JSON.stringify(body):undefined});
  const result=await response.json();if(!response.ok)throw new Error(result.error || 'לא ניתן להשלים את הפעולה');return result;
}
const dateText=value=>new Date(value).toLocaleDateString('he-IL',{day:'numeric',month:'long',year:'numeric'});
const timeText=value=>new Date(value).toLocaleString('he-IL');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function Icon({name,size=20}) {
  const paths={check:'m5 12 4 4L19 6',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M16 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',clock:'M12 8v4l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',settings:'M12 3v3 M12 18v3 M3 12h3 M18 12h3 M6 6l2 2 M16 16l2 2 M6 18l2-2 M16 8l2-2 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',plus:'M12 5v14 M5 12h14',upload:'M12 16V3 m-5 5 5-5 5 5 M4 16v5h16v-5',print:'M6 9V3h12v6 M6 18H3V9h18v9h-3 M6 14h12v7H6z',download:'M12 3v13 m-5-5 5 5 5-5 M4 17v4h16v-4',book:'M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3z M12 5v17',lock:'M5 10h14v11H5z M8 10V7a4 4 0 0 1 8 0v3',logout:'M9 3H3v18h6 M12 12h9 m-4-4 4 4-4 4'};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] || paths.check}/></svg>;
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>;}
function Dialog({title,onClose,children,wide=false}){
  const ref=useRef(null);
  useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('input,select,button')?.focus();return()=>previous?.focus();},[]);
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const elements=[...ref.current.querySelectorAll('button,input,select,textarea,a[href]')].filter(el=>!el.disabled);const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section ref={ref} className={`dialog ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" aria-label="סגירה" onClick={onClose}>×</button></header>{children}</section></div>;
}
function FormDialog({title,onClose,onSubmit,children,label='שמירה'}){const[busy,setBusy]=useState(false),[error,setError]=useState('');return <Dialog title={title} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSubmit(Object.fromEntries(new FormData(e.currentTarget)));onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}}>{children}{error&&<p className="error" role="alert">{error}</p>}<footer><button className="primary" disabled={busy}>{busy?'שומר…':label}</button><button type="button" onClick={onClose}>ביטול</button></footer></form></Dialog>;}
function App(){
  const [config,setConfig]=useState(null),[user,setUser]=useState(null),[courses,setCourses]=useState([]),[courseId,setCourseId]=useState(''),[detail,setDetail]=useState(null),[meetingId,setMeetingId]=useState(''),[meeting,setMeeting]=useState(null),[tab,setTab]=useState('attendance'),[dialog,setDialog]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logs,setLogs]=useState([]),[search,setSearch]=useState(''),[print,setPrint]=useState(null);
  const slipToken=new URLSearchParams(location.hash.replace(/^#/, '')).get('slip');
  const execute=async fn=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const loadCourses=async preferred=>{const c=await request('/courses');setCourses(c);setCourseId(previous=>preferred || previous || c[0]?.id || '');};
  const loadDetail=async()=>{if(courseId){const d=await request(`/courses/${courseId}`);setDetail(d);setMeetingId(previous=>d.meetings.some(m=>m.id===previous)?previous:d.meetings[0]?.id || '');}};
  const loadMeeting=async()=>{if(meetingId)setMeeting(await request(`/meetings/${meetingId}`));else setMeeting(null);};
  const refresh=async()=>{await loadCourses();await loadDetail();await loadMeeting();};
  useEffect(()=>{request('/config').then(setConfig).catch(e=>setError(e.message));if(session)request('/me').then(setUser).catch(()=>{session='';sessionStorage.removeItem('lecturer-session');});},[]);
  useEffect(()=>{if(user)execute(()=>loadCourses());},[user]);
  useEffect(()=>{setDetail(null);setMeeting(null);setMeetingId('');if(user&&courseId)execute(loadDetail);},[courseId]);
  useEffect(()=>{if(user)execute(loadMeeting);},[meetingId]);
  useEffect(()=>{if(tab==='audit'&&courseId)execute(async()=>setLogs(await request(`/courses/${courseId}/audit`)));},[tab,courseId,detail]);
  const signedIn=result=>{session=result.token;sessionStorage.setItem('lecturer-session',session);setUser(result.user);};
  useEffect(()=>{
    if(!config?.supabase || user || slipToken)return;
    let cancelled=false;
    (async()=>{
      try {
        const params=new URLSearchParams(location.search);
        if(params.has('error'))throw new Error('ההתחברות בוטלה או נכשלה. אפשר לנסות שוב.');
        const client=await authClient(config.supabase);
        const {data,error}=await client.auth.getSession();if(error)throw error;
        if(data.session&&!cancelled){const result=await request('/auth/supabase',{accessToken:data.session.access_token});if(!cancelled){signedIn(result);history.replaceState(null,'',location.pathname);}}
      }catch(e){if(!cancelled)setError(e.message);}
    })();return()=>{cancelled=true;};
  },[config,user]);
  useEffect(()=>{
    if(!config?.googleClientId || user || slipToken)return;
    const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>{window.google.accounts.id.initialize({client_id:config.googleClientId,callback:result=>execute(async()=>signedIn(await request('/auth/google',{credential:result.credential})))});window.google.accounts.id.renderButton(document.getElementById('google-signin'),{theme:'outline',size:'large',text:'signin_with',locale:'he'});};document.head.append(script);return()=>script.remove();
  },[config,user]);
  useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(id);},[message]);
  if(slipToken)return <Student token={slipToken}/>;
  if(!user)return <main className="login"><div className="login-card"><div className="brand-mark"><Icon name="check" size={30}/></div><h1>נוכחות</h1><p>ניהול נוכחות בקורסים</p><div className="login-separator"/><h2>כניסת מרצים</h2><p className="muted">באמצעות חשבון Google שאושר למערכת</p><div id="google-signin"/>{config?.supabase&&<button className="google-button" disabled={busy} onClick={()=>execute(()=>startGoogleLogin(config.supabase,config.frontend))}>כניסה באמצעות Google</button>}{config&&!config.googleClientId&&!config.supabase&&<p className="notice">כניסת Google תהיה זמינה לאחר הגדרת שירות ההתחברות.</p>}{config?.developmentLogin&&<><button className="primary" disabled={busy} onClick={()=>execute(async()=>signedIn(await request('/auth/dev',{})))}>פתיחת סביבת ניסיון מקומית</button><small>סביבת פיתוח בלבד · אינה זמינה באתר ציבורי</small></>}{error&&<p className="error">{error}</p>}<div className="login-note"><Icon name="lock"/><span>הגישה לרשימות ולנוכחות מוגבלת למרצים מורשים</span></div></div></main>;
  const c=detail?.course,m=meeting?.meeting;
  const attendees=new Set(meeting?.attendance.map(a=>a.student_id));
  const students=(detail?.students || []).filter(s=>`${s.first_name} ${s.last_name} ${s.identifier}`.includes(search));
  const active=m&&!m.closed&&(!m.opens||Date.now()>=Date.parse(m.opens))&&(!m.closes||Date.now()<=Date.parse(m.closes));
  const printSlips=async({count})=>{
    const result=await request(`/meetings/${meetingId}/slips`,{count:Number(count)});
    const slips=await Promise.all(result.slips.map(async s=>{const url=`${config.frontend}/#slip=${s.token}`;return {...s,url,image:await QRCode.toDataURL(url,{width:220,margin:1,errorCorrectionLevel:'M'})};}));setPrint({slips,course:c,meeting:m});setMessage('הפתקים הופקו. שמרו כ־PDF או הדפיסו לפני סגירת החלון.');await refresh();
  };
  const exportCsv=()=>{
    const rows=[['מספר סטודנט','שם פרטי','שם משפחה','נוכחות','מועד רישום'],...(detail?.students || []).map(s=>{const a=meeting?.attendance.find(a=>a.student_id===s.id);return [s.identifier,s.first_name,s.last_name,a?'נוכח':'לא נרשם',a?.updated || ''];})];
    download('\uFEFF'+Papa.unparse(rows,{escapeFormulae:true}),'text/csv;charset=utf-8',`attendance-${c.code}-${m.date}.csv`);
  };
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Icon name="check"/></div><span>נוכחות<small>מרחב המרצה</small></span></div><div className="sidebar-label">הקורסים שלי</div><label className="sr-only" htmlFor="course">בחירת קורס</label><select id="course" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">בחירת קורס</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} · {c.group_name}</option>)}</select><button className="new-course" onClick={()=>setDialog('course')}><Icon name="plus"/> קורס חדש</button><nav>{[['attendance','grid','נוכחות'],['roster','people','רשימת סטודנטים'],['audit','clock','יומן פעילות'],['settings','settings','הגדרות והרשאות']].map(([key,icon,title])=><button key={key} className={tab===key?'selected':''} onClick={()=>setTab(key)}><Icon name={icon}/>{title}</button>)}</nav><div className="sidebar-bottom">{config?.developmentLogin&&<span className="demo-tag">סביבת ניסיון מקומית</span>}<div className="user-row"><div className="avatar">{user.email[0].toUpperCase()}</div><span><b>{user.role==='admin'?'מנהל מערכת':'מרצה'}</b><small dir="ltr">{user.email}</small></span><button className="icon-button" aria-label="יציאה" onClick={()=>execute(async()=>{await signOutGoogle(config?.supabase);await request('/auth/logout',{});session='';sessionStorage.removeItem('lecturer-session');setUser(null);})}><Icon name="logout"/></button></div></div></aside>
  <main className="workspace"><header className="topbar"><span><Icon name="book"/> {c?`${c.code} · קבוצה ${c.group_name}`:'הקורסים שלי'}</span><span className="muted">{dateText(new Date())}</span></header><div className="content">{error&&<div className="error alert" role="alert">{error}<button onClick={()=>setError('')} aria-label="סגירה">×</button></div>}{message&&<div className="success alert" role="status">{message}</div>}
  {!c&&tab==='settings'&&user.role==='admin'&&<AccessPanel onChange={refresh}/>}
  {!c?<div className="empty"><div className="empty-icon"><Icon name="book" size={40}/></div><h1>{busy?'טוען את הקורס…':'כל הנוכחות, במקום אחד'}</h1><p>צרו קורס וקבוצה, ייבאו את רשימת הסטודנטים והפיקו פתקים למפגש הראשון.</p><button className="primary" onClick={()=>setDialog('course')}><Icon name="plus"/>יצירת קורס</button></div>:<>
  <div className="page-heading"><div><div className="eyebrow">{c.code} / קבוצה {c.group_name}</div><h1>{tab==='attendance'?c.name:tab==='roster'?'רשימת סטודנטים':tab==='audit'?'יומן פעילות':'הגדרות והרשאות'}</h1><p className="muted">{tab==='attendance'?'מפגשים, פתקים ורישומי נוכחות':c.name}</p></div>{tab==='attendance'&&<button className="primary" onClick={()=>setDialog('meeting')}><Icon name="plus"/>מפגש חדש</button>}{tab==='roster'&&<button className="primary" onClick={()=>setDialog('import')}><Icon name="upload"/>ייבוא מ־Moodle</button>}</div>
  {tab==='attendance'&&<><div className="stats"><Stat value={detail.students.length} label="סטודנטים בקבוצה" icon="people"/><Stat value={meeting?.attendance.length || 0} label="נרשמו במפגש" icon="check"/><Stat value={detail.students.length?`${Math.round((meeting?.attendance.length || 0)/detail.students.length*100)}%`:'—'} label="שיעור נוכחות" icon="grid"/><Stat value={detail.meetings.length} label="מפגשים בקורס" icon="book"/></div><section className="panel"><div className="panel-head"><div><h2>המפגש הנוכחי</h2><p className="muted">בחרו מפגש כדי לנהל את הרישום</p></div><select aria-label="בחירת מפגש" value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">בחירת מפגש</option>{detail.meetings.map(m=><option key={m.id} value={m.id}>{m.title} · {dateText(m.date)}</option>)}</select></div>{m?<><div className="meeting-band"><div><span className={`badge ${active?'open':'closed'}`}>{active?'הרישום פתוח':'הרישום סגור'}</span><h3>{m.title}</h3><span>{dateText(m.date)} · {m.opens||m.closes?'חלון רישום מוגדר':'ללא הגבלת זמן'}</span></div><div className="actions"><button onClick={()=>setDialog('slips')}><Icon name="print"/>הפקת פתקים</button><button onClick={()=>setDialog('window')}><Icon name="clock"/>חלון רישום</button><button onClick={()=>execute(async()=>{await request(`/meetings/${m.id}`,{closed:!m.closed,opens:m.opens,closes:m.closes},'PATCH');await refresh();})}><Icon name="lock"/>{m.closed?'פתיחת רישום':'סגירת רישום'}</button></div></div><div className="table-toolbar"><h2>רישומי נוכחות <span className="count">{meeting.attendance.length}</span></h2><div className="actions"><button onClick={()=>setDialog('manual')}>רישום ידני</button><button onClick={exportCsv}><Icon name="download"/>ייצוא CSV</button></div></div><Roster students={detail.students} attendance={meeting.attendance} showStatus/>{!detail.students.length&&<p className="table-empty">כדי להתחיל, ייבאו את רשימת הסטודנטים בלשונית ״רשימת סטודנטים״.</p>}</>:<div className="section-empty"><Icon name="clock" size={30}/><h3>המפגש הראשון מתחיל כאן</h3><p>צרו מפגש והפיקו פתק QR נפרד לכל סטודנט.</p><button onClick={()=>setDialog('meeting')}>יצירת מפגש</button></div>}</section><p className="footnote">יש לחלק פתק אחד לכל נוכח. ניתן לתקן את הרישום באמצעות אותו פתק כל עוד הרישום פתוח.</p></>}
  {tab==='attendance'&&meeting?.attendance.length>0&&<button onClick={()=>setDialog('correction')}>תיקון רישום קיים</button>}
  {tab==='attendance'&&m&&<SlipsPanel slips={meeting.slips || []} meetingId={m.id} onChange={refresh}/>}
  {tab==='roster'&&<section className="panel"><div className="table-toolbar"><h2>{detail.students.length} סטודנטים</h2><input aria-label="חיפוש סטודנט" placeholder="חיפוש לפי שם או מספר סטודנט" value={search} onChange={e=>setSearch(e.target.value)}/></div><Roster students={students}/>{!students.length&&<div className="section-empty"><Icon name="people" size={32}/><h3>רשימת הסטודנטים עדיין ריקה</h3><p>ייבאו קובץ CSV או Excel שהורדתם מ־Moodle.</p><button onClick={()=>setDialog('import')}>ייבוא רשימה</button></div>}<div className="panel-note">ייבוא נוסף מעדכן שמות ומוסיף סטודנטים. היסטוריית הנוכחות נשמרת.</div></section>}
  {tab==='audit'&&<section className="panel"><div className="panel-head"><h2>פעולות אחרונות</h2><span className="muted">יומן שאינו ניתן לעריכה · עד 500 אירועים</span></div><div className="table-scroll"><table><thead><tr><th>מועד</th><th>פעולה</th><th>מבצע</th><th>פרטים</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{timeText(l.at)}</td><td>{actionLabel(l.action)}</td><td dir="auto">{l.actor==='student'?'סטודנט':l.actor}</td><td><code dir="ltr">{l.details}</code></td></tr>)}</tbody></table></div>{!logs.length&&<p className="table-empty">אין אירועים להצגה.</p>}</section>}
  {tab==='settings'&&<div className="settings-grid"><section className="panel settings-card"><h2>צוות הקורס</h2><p className="muted">הגישה מוגבלת לחשבונות שהוזמנו לקורס.</p>{detail.members.map(member=><div className="member" key={member.email}><div className="avatar">{member.email[0].toUpperCase()}</div><span dir="ltr">{member.email}</span>{member.email===c.owner?<span className="badge">בעל הקורס</span>:c.owner===user.email&&<button onClick={()=>setDialog({type:'revoke-member',email:member.email})}>ביטול גישה</button>}</div>)}{c.owner===user.email&&<button onClick={()=>setDialog('member')}><Icon name="plus"/>הוספת מרצה או מתרגל</button>}</section>{user.role==='admin'&&<AccessPanel onChange={refresh}/>}<section className="panel settings-card"><h2>הדפסה ופרטיות</h2><p>פתק QR מאפשר רישום ותיקון נוכחות. יש לשמור עליו ולא לשתף צילום שלו.</p><p className="muted">ללא הזדהות סטודנטים, השיטה נשענת על חלוקה מבוקרת של פתק אחד לאדם ואינה מבטיחה מניעת התחזות.</p></section></div>}
  </>}</div></main>
  {dialog==='course'&&<CourseCreator onClose={()=>setDialog('')} onCreate={async data=>{const c=await request('/courses/with-roster',data);await loadCourses(c.id);setTab('roster');setMessage(`הקורס נוצר עם ${c.student_count} משתתפים`);}}/>}
  {dialog==='meeting'&&<FormDialog title="מפגש חדש" onClose={()=>setDialog('')} onSubmit={async data=>{const m=await request(`/courses/${courseId}/meetings`,data);await loadDetail();setMeetingId(m.id);}} label="יצירת מפגש"><Field label="שם המפגש"><input name="title" required placeholder="למשל: שיעור 1"/></Field><Field label="תאריך"><input name="date" type="date" defaultValue={today()} required/></Field><p className="notice">הרישום פתוח ללא הגבלת זמן כברירת מחדל. אפשר להגדיר חלון רישום לאחר יצירת המפגש.</p></FormDialog>}
  {dialog==='slips'&&<FormDialog title="הפקת פתקים להדפסה" onClose={()=>setDialog('')} onSubmit={printSlips} label="הפקת פתקים"><Field label="מספר פתקים"><input name="count" type="number" min="1" max="300" defaultValue={Math.min(detail.students.length || 30,300)} required/></Field><p className="notice">כל פתק נפרד וניתן לרישום אחד. עד 300 פתקים למפגש. קישורי הפתקים מוצגים רק בעת ההפקה.</p></FormDialog>}
  {dialog==='window'&&<FormDialog title="חלון רישום" onClose={()=>setDialog('')} onSubmit={async data=>{await request(`/meetings/${m.id}`,{closed:!!m.closed,opens:data.opens||null,closes:data.closes||null},'PATCH');await refresh();}}><Field label="פתיחה (אופציונלי)"><input type="datetime-local" name="opens" defaultValue={localDateTime(m.opens)}/></Field><Field label="סגירה (אופציונלי)"><input type="datetime-local" name="closes" defaultValue={localDateTime(m.closes)}/></Field><p className="muted">השאירו ריק לרישום ללא הגבלת זמן. הזמנים מוצגים לפי השעון המקומי שלכם.</p></FormDialog>}
  {dialog==='manual'&&<FormDialog title="רישום נוכחות ידני" onClose={()=>setDialog('')} onSubmit={async data=>{await request(`/meetings/${meetingId}/manual`,data);await refresh();}}><Field label="סטודנט"><select name="studentId" required><option value="">בחירת סטודנט</option>{detail.students.filter(s=>!attendees.has(s.id)).map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.identifier}</option>)}</select></Field><Field label="סיבת הרישום"><textarea name="reason" required placeholder="למשל: הטלפון לא היה זמין"/></Field><p className="muted">הפעולה ושם המרצה יתועדו ביומן הפעילות.</p></FormDialog>}
  {['member','teacher'].includes(dialog)&&<FormDialog title={dialog==='member'?'הוספת איש צוות לקורס':'הרשאת מרצה'} onClose={()=>setDialog('')} onSubmit={async data=>{await request(dialog==='member'?`/courses/${courseId}/members`:'/teachers',data);await refresh();setMessage('ההרשאה נוספה');}}><Field label="כתובת המייל של חשבון Google"><input type="email" name="email" dir="ltr" required/></Field></FormDialog>}
  {dialog==='correction'&&<FormDialog title="תיקון רישום קיים" onClose={()=>setDialog('')} onSubmit={async data=>{await request(`/attendance/${data.attendanceId}`,data,'PATCH');await refresh();setMessage('הרישום עודכן והתיקון תועד ביומן');}}><Field label="הרישום לתיקון"><select name="attendanceId" required><option value="">בחירת רישום</option>{meeting.attendance.map(a=><option key={a.id} value={a.id}>{a.first_name} {a.last_name} · {a.identifier}</option>)}</select></Field><Field label="הסטודנט הנכון"><select name="studentId" required><option value="">בחירת סטודנט</option>{detail.students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.identifier}</option>)}</select></Field><Field label="סיבת התיקון"><textarea name="reason" required/></Field></FormDialog>}
  {dialog==='import'&&<Importer onClose={()=>setDialog('')} onImport={async rows=>{await request(`/courses/${courseId}/students`,{students:rows});await refresh();setMessage(`יובאו ${rows.length} סטודנטים`);}}/>}
  {dialog?.type==='revoke-member'&&<FormDialog title="ביטול גישה לקורס" label="ביטול הגישה" onClose={()=>setDialog('')} onSubmit={async()=>{await request(`/courses/${courseId}/members/revoke`,{email:dialog.email});await refresh();setMessage('הגישה לקורס בוטלה');}}><p dir="ltr">{dialog.email}</p><p>ההרשאה לקורס תבוטל מיד. רישומי הנוכחות ויומן הפעילות יישמרו.</p></FormDialog>}
  {print&&<div className="print-overlay"><div className="print-controls"><h2>פתקי נוכחות · {print.slips.length} פתקים</h2><p>שמרו כ־PDF או הדפיסו. לאחר סגירת החלון לא ניתן לשחזר את הקודים.</p><button className="primary" onClick={()=>window.print()}><Icon name="print"/>הדפסה / שמירה כ־PDF</button><button onClick={()=>print.readyToClose?setPrint(null):setPrint({...print,readyToClose:true})}>{print.readyToClose?'הפתקים נשמרו — סיום':'סיום'}</button>{print.readyToClose&&<p className="notice">לפני הסיום, ודאו שהדפסתם או שמרתם את הפתקים. הקישורים לא יוצגו שוב.</p>}</div><div className="slip-grid">{print.slips.map(s=><article className="slip" key={s.number}><div><b>{print.course.name}</b><span>{print.course.code} · קבוצה {print.course.group_name}</span><span>{print.meeting.title} · {dateText(print.meeting.date)}</span></div><img src={s.image} alt={`קוד QR לפתק ${s.number}`}/><strong>פתק {String(s.number).padStart(3,'0')}</strong><small>סריקה · בחירת שם · אישור נוכחות</small></article>)}</div></div>}
  </div>;
}
function AccessPanel({onChange}) {
  const [teachers,setTeachers]=useState([]),[error,setError]=useState(''),[dialog,setDialog]=useState(null);
  const load=()=>request('/teachers').then(setTeachers).catch(e=>setError(e.message));
  useEffect(()=>{load();},[]);
  const change=async(path,body)=>{await request(path,body);await load();await onChange();};
  return <section className="panel settings-card"><h2>ניהול הרשאות מרצים</h2><p className="muted">רק כתובות שאושרו כאן יכולות להיכנס. הרשאה לקורס מסוים ניתנת בנפרד.</p>{error&&<p className="error">{error}</p>}<div className="access-list">{teachers.map(t=><div className="access-row" key={t.email}><div><b dir="ltr">{t.email}</b><small>{t.role==='admin'?'מנהל מערכת':t.active?'מרצה פעיל':'הגישה הושבתה'} · {t.course_count} קורסים</small></div>{t.role!=='admin'&&<button onClick={()=>setDialog({type:t.active?'revoke':'restore',email:t.email})}>{t.active?'השבתת גישה':'הפעלת גישה'}</button>}</div>)}</div><button onClick={()=>setDialog({type:'add'})}><Icon name="plus"/>אישור מרצה חדש</button>
  {dialog?.type==='add'&&<FormDialog title="אישור מרצה חדש" onClose={()=>setDialog(null)} onSubmit={data=>change('/teachers',data)}><Field label="כתובת המייל של חשבון Google"><input name="email" type="email" dir="ltr" required/></Field><p className="muted">הפעולה מאשרת כניסה למערכת. היא אינה שולחת הודעת מייל.</p></FormDialog>}
  {dialog&&dialog.type!=='add'&&<FormDialog title={dialog.type==='revoke'?'השבתת גישה למערכת':'הפעלת גישה למערכת'} label={dialog.type==='revoke'?'השבתת גישה':'הפעלת גישה'} onClose={()=>setDialog(null)} onSubmit={()=>change(dialog.type==='revoke'?'/teachers/revoke':'/teachers',{email:dialog.email})}><p dir="ltr">{dialog.email}</p><p>{dialog.type==='revoke'?'הכניסה והגישה לכל הקורסים ייחסמו מיד, כולל התחברויות קיימות. נתוני הקורסים והנוכחות יישמרו.':'הכניסה תאושר מחדש, כולל הרשאות הקורסים שנשמרו לפני ההשבתה.'}</p></FormDialog>}
  </section>;
}
function SlipsPanel({slips,meetingId,onChange}) {
  const [dialog,setDialog]=useState(false),[selected,setSelected]=useState([]);
  useEffect(()=>{setSelected([]);setDialog(false);},[meetingId]);
  const unused=slips.filter(s=>!s.used&&!s.revoked),used=slips.filter(s=>s.used),revoked=slips.filter(s=>s.revoked);
  return <section className="panel slips-panel"><div className="panel-head"><h2>ניהול פתקים</h2><button disabled={!unused.length} onClick={()=>setDialog(true)}>ביטול פתקים שלא נוצלו</button></div><div className="slip-summary"><span>{used.length} נרשמו</span><span>{unused.length} פעילים וטרם נרשמו</span><span>{revoked.length} בוטלו</span></div><div className="panel-note">בחרו לפי המספר המודפס על הפתק. ביטול פתק אינו מוחק רישום נוכחות קיים.</div>
  {dialog&&<FormDialog title="ביטול פתקים" label={`ביטול ${selected.length} פתקים`} onClose={()=>setDialog(false)} onSubmit={async data=>{if(!selected.length)throw new Error('יש לבחור לפחות פתק אחד');await request(`/meetings/${meetingId}/slips/revoke`,{numbers:selected,reason:data.reason});setSelected([]);await onChange();}}><p>בחרו פתקים שלא חולקו, שאבדו או שהקישור שלהם נחשף. לא ניתן להשתמש בפתק לאחר ביטולו.</p><div className="slip-picker">{unused.map(s=><label key={s.number}><input type="checkbox" checked={selected.includes(s.number)} onChange={e=>setSelected(e.target.checked?[...selected,s.number]:selected.filter(n=>n!==s.number))}/>פתק {String(s.number).padStart(3,'0')}</label>)}</div><Field label="סיבת הביטול"><textarea name="reason" required placeholder="למשל: פתקים שנותרו לאחר חלוקה"/></Field><p className="muted">הביטול מתועד ביומן. אפשר להפיק פתקים חלופיים עד למגבלה של 300 פתקים פעילים במפגש.</p></FormDialog>}
  </section>;
}
function Stat({value,label,icon}){return <article className="stat"><span className="stat-icon"><Icon name={icon}/></span><div><strong>{value}</strong><span>{label}</span></div></article>;}
function Roster({students,attendance=[],showStatus=false}){return <div className="table-scroll"><table><thead><tr><th>סטודנט</th><th>מספר סטודנט / ת״ז</th>{showStatus&&<><th>נוכחות</th><th>מועד רישום</th><th>פתק</th></>}</tr></thead><tbody>{students.map(s=>{const a=attendance.find(a=>a.student_id===s.id);return <tr key={s.id}><td><div className="student-cell"><span className="initials">{s.first_name[0]}{s.last_name[0]}</span><b>{s.first_name} {s.last_name}</b></div></td><td className="identifier" dir="ltr">{s.identifier}</td>{showStatus&&<><td><span className={`badge ${a?'present':'absent'}`}>{a?'נוכח':'טרם נרשם'}</span></td><td>{a?timeText(a.updated):'—'}</td><td>{a?.slip_number || (a?'ידני':'—')}</td></>}</tr>;})}</tbody></table></div>;}
function localDateTime(value){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function actionLabel(action){return {'course.created':'יצירת קורס','course.viewed':'צפייה בקורס','meeting.created':'יצירת מפגש','slips.issued':'הפקת פתקים','slips.revoked':'ביטול פתקים','roster.imported':'ייבוא סטודנטים','attendance.registered':'רישום נוכחות','attendance.corrected':'תיקון נוכחות','attendance.teacher_corrected':'תיקון נוכחות בידי מרצה','attendance.rejected':'בקשה שנדחתה','attendance.manual':'רישום ידני','meeting.settings_changed':'שינוי הגדרות מפגש','course.member_added':'הוספת איש צוות','course.member_revoked':'ביטול גישה לקורס','request.rejected':'פעולה שנדחתה'}[action] || action;}

function CourseCreator({onClose,onCreate}) {
  const [course,setCourse]=useState({name:'',code:'',group_name:'',year:'',semester:'א׳'});
  const fields=[['name','שם הקורס'],['code','מספר קורס'],['group_name','מספר קבוצה'],['year','שנת לימודים']];
  const valid=fields.every(([key])=>course[key].trim());
  return <Importer title="יצירת קורס עם רשימת משתתפים" label="יצירת הקורס ושמירת המשתתפים" disabled={!valid} onClose={onClose} onImport={students=>onCreate({...course,students})}><p className="muted">הקורס והרשימה יישמרו יחד רק לאחר האישור. כל המשתתפים בקובץ ייכללו בקבוצה שתבחרו, ללא סינון לפי תפקיד או קבוצת Moodle.</p><div className="mapping">{fields.map(([key,label])=><Field key={key} label={label}><input required value={course[key]} placeholder={key==='year'?'למשל: תשפ״ז':''} onChange={e=>setCourse({...course,[key]:e.target.value})}/></Field>)}<Field label="סמסטר"><select value={course.semester} onChange={e=>setCourse({...course,semester:e.target.value})}><option>א׳</option><option>ב׳</option><option>קיץ</option><option>שנתי</option></select></Field></div></Importer>;
}
function Importer({onClose,onImport,children,title='ייבוא רשימת סטודנטים',label='אישור ייבוא',disabled=false}) {
  const[data,setData]=useState([]),[headers,setHeaders]=useState([]),[mapping,setMapping]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=async file=>{if(!file)return;setError('');setBusy(true);try{
    if(file.size>5*1024*1024)throw new Error('הקובץ גדול מדי. המגבלה היא 5MB.');
    let rows;
    if(/\.xlsx$/i.test(file.name)){const {default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];rows=[];sheet.eachRow(row=>{const values=[];for(let i=1;i<=sheet.columnCount;i++){const cell=row.getCell(i);values.push(cell.value==null?'':typeof cell.value==='number'&&/^[0]+$/.test(cell.numFmt)?String(cell.value).padStart(cell.numFmt.length,'0'):cell.text);}rows.push(values);});}
    else if(/\.csv$/i.test(file.name)){const result=Papa.parse((await file.text()).replace(/^\uFEFF/,''),{skipEmptyLines:'greedy',dynamicTyping:false});if(result.errors.length)throw new Error('לא ניתן לקרוא את קובץ ה־CSV. בדקו את המבנה.');rows=result.data;}
    else throw new Error('בחרו קובץ CSV או XLSX.');
    if(rows.length<2)throw new Error('לא נמצאו שורות סטודנטים בקובץ');if(rows.length>2001)throw new Error('אפשר לייבא עד 2000 סטודנטים בכל פעם');
    const heads=rows[0].map((h,i)=>String(h).trim() || `עמודה ${i+1}`);setHeaders(heads);setData(rows.slice(1));const find=regexp=>String(heads.findIndex(h=>regexp.test(h)));setMapping({first_name:find(/שם פרטי|first.?name/i),last_name:find(/שם משפחה|last.?name|surname/i),identifier:find(/תעודת|ת״ז|ת.ז|מספר סטודנט|id.?number|student.?id|username/i)});
  }catch(e){setError(e.message);setData([]);}finally{setBusy(false);}};
  const rows=data.map(row=>Object.fromEntries(['identifier','first_name','last_name'].map(k=>[k,String(row[Number(mapping[k])] ?? '').trim()])));
  const counts=new Map();rows.forEach(r=>counts.set(r.identifier,(counts.get(r.identifier)||0)+1));
  const invalid=rows.filter(r=>!r.identifier||!r.first_name||!r.last_name||counts.get(r.identifier)>1).length;
  const ready=data.length&&Object.values(mapping).every(v=>Number(v)>=0)&&new Set(Object.values(mapping)).size===3;
return <Dialog title={title} onClose={onClose} wide>{children}<div className="upload-zone"><Icon name="upload" size={30}/><b>קובץ רשימת משתתפים מ־Moodle</b><span>CSV או Excel ‏(XLSX) · עד 5MB</span><input type="file" accept=".csv,.xlsx" aria-label="בחירת קובץ סטודנטים" onChange={e=>load(e.target.files[0])}/></div>{data.length>0&&<><h3>התאמת עמודות</h3><div className="mapping">{[['first_name','שם פרטי'],['last_name','שם משפחה'],['identifier','מספר סטודנט / ת״ז']].map(([key,label])=><Field key={key} label={label}><select value={mapping[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="-1">בחירת עמודה</option>{headers.map((h,i)=><option key={i} value={String(i)}>{h}</option>)}</select></Field>)}</div><p className={invalid?'error':'success'}>{data.length} שורות · {invalid?`${invalid} שורות חסרות או כפולות — יש לתקן לפני הייבוא`:'לא נמצאו כפילויות או נתונים חסרים'}</p><div className="table-scroll"><table><thead><tr><th>שם פרטי</th><th>שם משפחה</th><th>מזהה</th></tr></thead><tbody>{rows.slice(0,8).map((r,i)=><tr key={i}><td>{r.first_name}</td><td>{r.last_name}</td><td dir="ltr">{r.identifier}</td></tr>)}</tbody></table></div><p className="muted">תצוגה מקדימה של 8 השורות הראשונות. רשומות קיימות יעודכנו ללא מחיקת נוכחות.</p><p className="muted">אם Excel כבר מחק אפסים מובילים מהמזהים, לא ניתן לשחזר אותם כאן. ייבאו עמודת מזהים שמוגדרת כטקסט.</p></>}{error&&<p className="error" role="alert">{error}</p>}<footer><button className="primary" disabled={disabled||!ready||!!invalid||busy} onClick={async()=>{setBusy(true);try{await onImport(rows);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'שומר…':label}</button><button onClick={onClose}>ביטול</button></footer></Dialog>;
}

function Student({token}) {
  const[data,setData]=useState(null),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[remember,setRemember]=useState(true),[editing,setEditing]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{request(`/slip/${token}`).then(d=>{setData(d);let stored;try{stored=localStorage.getItem(`student-${d.courseId}`);}catch{}setSelected(d.previous?.studentId || (d.students.some(s=>s.id===stored)?stored:''));}).catch(e=>setError(e.message));},[token]);
  const s=data?.students.find(s=>s.id===selected);const options=data?.students.filter(s=>`${s.first_name} ${s.last_name}`.includes(search)) || [];
  return <main className="student-page"><div className="student-brand"><div className="brand-mark"><Icon name="check"/></div><b>נוכחות</b></div><section className="student-card">{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>טוען את פרטי המפגש…</p>}{data&&<><div className="eyebrow">{data.course.code} · קבוצה {data.course.group_name}</div><h1>{data.course.name}</h1><p className="muted">{data.meeting.title} · {dateText(data.meeting.date)}</p><div className="student-divider"/>{result?<div className="confirmed"><div className="confirmed-icon"><Icon name="check" size={32}/></div><h2>{result.corrected?'הנוכחות עודכנה':'הנוכחות נרשמה'}</h2><p>{result.student.name}</p><p dir="ltr">{result.student.identifier}</p><button onClick={()=>{setResult(null);setEditing(true);}}>תיקון הפרטים</button></div>:<>{data.previous&&!editing?<><span className="badge present">הפתק כבר נרשם</span><h2>{data.previous.name}</h2><p>מספר שנרשם: <b dir="ltr">{data.previous.identifier}</b></p><p className="muted">{timeText(data.previous.updated)}</p>{data.isOpen&&<button className="primary" onClick={()=>setEditing(true)}>תיקון הפרטים</button>}</>:data.isOpen?<><h2>{editing?'תיקון רישום':'אישור נוכחות'}</h2>{s&&!editing?<div className="remembered"><p>רישום נוכחות עבור</p><strong>{s.first_name} {s.last_name}</strong><button className="link-button" onClick={()=>{setSelected('');setEditing(true);}}>זה לא אני — החלפת משתמש</button></div>:<><Field label="חיפוש שם פרטי ומשפחה"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="התחילו להקליד את השם"/></Field><div className="student-options" role="group" aria-label="בחירת סטודנט">{options.slice(0,50).map(s=><button key={s.id} className={selected===s.id?'chosen':''} onClick={()=>setSelected(s.id)}><span>{s.first_name} {s.last_name}</span><small>מזהה מסתיים ב־{s.suffix}</small></button>)}{!options.length&&<p>לא נמצא שם מתאים. פנו למרצה.</p>}{options.length>50&&<p className="muted">הקלידו שם כדי לצמצם את הרשימה.</p>}</div></>}<label className="checkbox"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>זכור אותי במכשיר הזה</label><button className="primary full" disabled={!selected||busy} onClick={async()=>{setBusy(true);setError('');try{const r=await request(`/slip/${token}/claim`,{studentId:selected});try{if(remember)localStorage.setItem(`student-${data.courseId}`,selected);else localStorage.removeItem(`student-${data.courseId}`);}catch{}setResult(r);setData(await request(`/slip/${token}`));}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'רושם…':editing?'עדכון נוכחות':'אישור נוכחות'}</button></>:null}{!data.isOpen&&<p className="notice">הרישום למפגש סגור. לתיקון או רישום נוסף יש לפנות למרצה.</p>}</>}<p className="footnote">פתק {String(data.number).padStart(3,'0')} · אין לשתף את הפתק או הקישור</p></>}</section></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
